/*
 * To Do API
 *
 * A To Do API example which demonstrate features in the OpenAPI 3.0 specification
 *
 * The version of the OpenAPI document: 1.0.24
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ToDoApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ToDoApiTests
    {
        private ToDoApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ToDoApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ToDoApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' ToDoApi
            //Assert.IsInstanceOf(typeof(ToDoApi), instance);
        }

        
        /// <summary>
        /// Test CreateOne
        /// </summary>
        [Test]
        public void CreateOneTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ToDoItem toDoItem = null;
            //var response = instance.CreateOne(toDoItem);
            //Assert.IsInstanceOf(typeof(ToDoItem), response, "response is ToDoItem");
        }
        
        /// <summary>
        /// Test DeleteOne
        /// </summary>
        [Test]
        public void DeleteOneTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //instance.DeleteOne(id);
            
        }
        
        /// <summary>
        /// Test GetMany
        /// </summary>
        [Test]
        public void GetManyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //var response = instance.GetMany(limit);
            //Assert.IsInstanceOf(typeof(List<List>), response, "response is List<List>");
        }
        
        /// <summary>
        /// Test GetOne
        /// </summary>
        [Test]
        public void GetOneTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.GetOne(id);
            //Assert.IsInstanceOf(typeof(ToDoItem), response, "response is ToDoItem");
        }
        
    }

}
