/**
 * To Do API
 * A To Do API example which demonstrate features in the OpenAPI 3.0 specification
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ToDoItem model module.
 * @module model/ToDoItem
 * @version 1.0.0
 */
class ToDoItem {
    /**
     * Constructs a new <code>ToDoItem</code>.
     * @alias module:model/ToDoItem
     * @param name {String} 
     */
    constructor(name) { 
        
        ToDoItem.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>ToDoItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ToDoItem} obj Optional instance to populate.
     * @return {module:model/ToDoItem} The populated <code>ToDoItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ToDoItem();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ToDoItem.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ToDoItem.prototype['name'] = undefined;

/**
 * @member {String} status
 */
ToDoItem.prototype['status'] = undefined;






export default ToDoItem;

