name: Build and deploy Csharp SDK
on:
  workflow_dispatch:
jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '5.0.x' ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.6.0
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Authenticate with GitHub
      uses: actions/github-authenticate@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: cd src/clients/csharp && dotnet pack
    - name: Deploy to Github Packages
      run: cd src/clients/csharp && dotnet nuget push "Org.OpenAPITools/bin/Release/*.nupkg" --api-key ${{ github.token }} --source "github"