name: Build and deploy Csharp SDK
on:
  workflow_dispatch:
jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '4.5.x' ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Authenticate with GitHub
      run: dotnet nuget add source --username luisbar180492 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/luisbar180492/index.json"
    - name: Build
      run: cd src/sdks/csharp && chmod +x ./build.sh && ./build.sh
    - name: Deploy to Github Packages
      run: cd src/sdks/csharp && dotnet nuget push "Org.OpenAPITools/bin/Release/*.nupkg" --api-key ${{ github.token }} --source "github"