name: Build and deploy Javascript SDK
on:
  workflow_dispatch:
jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node version and registry url
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: cd src/sdks/javascript && npm i
      - name: Deploy to GitHub
        run: cd src/sdks/javascript && npm publish