name: Build and deploy java SDK
on:
  workflow_dispatch:
jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build and deploy to GitHub
        run: cd src/sdks/java && mvn deploy