/*
 * To Do API
 * A To Do API example which demonstrate features in the OpenAPI 3.0 specification
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.ToDoItem;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ToDoApi
 */
@Disabled
public class ToDoApiTest {

    private final ToDoApi api = new ToDoApi();

    /**
     * Creates a new to do item
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createOneTest() throws ApiException {
        ToDoItem toDoItem = null;
        ToDoItem response = api.createOne(toDoItem);
        // TODO: test validations
    }

    /**
     * Deletes a to do item by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteOneTest() throws ApiException {
        UUID id = null;
        api.deleteOne(id);
        // TODO: test validations
    }

    /**
     * Returns all to do items. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getManyTest() throws ApiException {
        Integer limit = null;
        List<List<ToDoItem>> response = api.getMany(limit);
        // TODO: test validations
    }

    /**
     * Returns a to do item by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getOneTest() throws ApiException {
        UUID id = null;
        ToDoItem response = api.getOne(id);
        // TODO: test validations
    }

}